// <auto-generated />
using Engage360plus.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Engage360plus.Migrations
{
    [DbContext(typeof(CRMDbContext))]
    [Migration("20250112154649_Navigation Properties")]
    partial class NavigationProperties
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Engage360plus.Models.Domain.Addresses", b =>
                {
                    b.Property<int>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AddressId"));

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Region")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AddressId");

                    b.ToTable("Addresses");

                    b.HasData(
                        new
                        {
                            AddressId = 1,
                            City = "Pune0",
                            Country = "India0",
                            PostalCode = "411072",
                            Region = "Pune0"
                        },
                        new
                        {
                            AddressId = 2,
                            City = "Pune1",
                            Country = "India1",
                            PostalCode = "411072",
                            Region = "Pune1"
                        },
                        new
                        {
                            AddressId = 3,
                            City = "Pune2",
                            Country = "India2",
                            PostalCode = "411072",
                            Region = "Pune2"
                        },
                        new
                        {
                            AddressId = 4,
                            City = "Pune0",
                            Country = "India0",
                            PostalCode = "411072",
                            Region = "Pune0"
                        },
                        new
                        {
                            AddressId = 5,
                            City = "Pune0",
                            Country = "India0",
                            PostalCode = "411072",
                            Region = "Pune0"
                        });
                });

            modelBuilder.Entity("Engage360plus.Models.Domain.CustomerDetails", b =>
                {
                    b.Property<int>("CustomerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerID"));

                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<int>("AddressesAddressId")
                        .HasColumnType("int");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductStatusStatusId")
                        .HasColumnType("int");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.HasKey("CustomerID");

                    b.HasIndex("AddressesAddressId");

                    b.HasIndex("ProductStatusStatusId");

                    b.ToTable("CustomerDetails");
                });

            modelBuilder.Entity("Engage360plus.Models.Domain.ProductStatus", b =>
                {
                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StatusId");

                    b.ToTable("ProductStatuses");

                    b.HasData(
                        new
                        {
                            StatusId = 1,
                            Name = "In Discussion"
                        },
                        new
                        {
                            StatusId = 2,
                            Name = "Paid"
                        },
                        new
                        {
                            StatusId = 3,
                            Name = "Rejected"
                        });
                });

            modelBuilder.Entity("Engage360plus.Models.Domain.CustomerDetails", b =>
                {
                    b.HasOne("Engage360plus.Models.Domain.Addresses", "Addresses")
                        .WithMany()
                        .HasForeignKey("AddressesAddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Engage360plus.Models.Domain.ProductStatus", "ProductStatus")
                        .WithMany()
                        .HasForeignKey("ProductStatusStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Addresses");

                    b.Navigation("ProductStatus");
                });
#pragma warning restore 612, 618
        }
    }
}
